version: "3.8"
services:
  proxy:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/home/app/webapp/staticfiles
      - social_static_volume:/home/app/webapp/social/staticfiles
      - global_static_volume:/home/app/webapp/global/staticfiles
      - ./nginx/index.html:/usr/share/nginx/html/gaze-tracker/index.html
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - cockpit
      - vocal
      - social
      - global
      # - gaze
      - questionnaire
  cockpit:
    image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/biomarker-cockpit:latest
    pull_policy: always
    container_name: cockpit
    ports:
      - "5000:80"
    restart: unless-stopped
  vocal:
    image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/vocal-biomarker
    # image: vocal-v1
    command: bash -c "python manage.py collectstatic --no-input && gunicorn vocal_biomaker.wsgi:application --bind 0.0.0.0:8001"
    container_name: vocal
    expose:
      - 8001
    # ports:
    #     - "8001:8001"
    volumes:
      - static_volume:/home/app/webapp/staticfiles
      - ./container_data/audios:/media/audios
    env_file:
      - ./.env
    restart: unless-stopped
  social:
    image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/social-biomaker:latest
    # image: social-v1
    command: bash -c "python manage.py collectstatic --no-input && gunicorn voice_capt.wsgi:application --bind 0.0.0.0:7000"
    volumes:
        - social_static_volume:/home/app/webapp/social/staticfiles
        - ./container_data/social/data.csv:/home/app/webapp/social/data.csv
    container_name: social
    expose:
      - 7000
    restart: unless-stopped
  global:
    command: bash -c "python manage.py collectstatic --no-input && gunicorn local_global.wsgi:application --bind 0.0.0.0:4000"
    image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/local-global-biomarker:latest
    # image: global-v1
    container_name: global
    volumes:
        - global_static_volume:/home/app/webapp/global/staticfiles
        - ./container_data/global/data.csv:/home/app/webapp/global/data.csv
    expose:
      - 4000
    restart: unless-stopped
  # gaze:
  #   image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/gaze-tracker:latest
  #   container_name: gaze
  #   ports:
  #     - "9000:80"
  #   restart: unless-stopped
  questionnaire:
    image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/biomarker-questionnaire:latest
    # image: aq
    container_name: questionnnaire
    ports:
      - "6000:80"
    restart: unless-stopped
volumes:
  static_volume:
  social_static_volume:
  global_static_volume:
