version: "3.8"
services:
    proxy:
        image: nginx
        container_name: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        restart: unless-stopped
    cockpit: 
        image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/biomarker-cockpit
        container_name: cockpit
        ports:
            - "5000:80"
        restart: unless-stopped
    vocal: 
        image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/vocal-biomarker
        container_name: vocal
        ports:
            - "8001:80"
        restart: unless-stopped
    social: 
        image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/social-biomaker
        container_name: social
        ports:
            - "7000:80"
        restart: unless-stopped
    global: 
        image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/local-global-biomarker
        container_name: global
        ports:
            - "4000:80"
        restart: unless-stopped
    gaze: 
        image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/gaze-tracker
        container_name: gaze
        ports:
            - "9000:80"
        restart: unless-stopped
    questionnaire:
        image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/biomarker-questionnaire:latest
        # image: aq
        container_name: questionnnaire
        ports:
            - "6000:80"
        restart: unless-stopped