version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    volumes:
      - db:/data/db
      - ./.mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - bm
volumes:
  db:
networks:
  bm:
    name: bm