version: "3.8"
services:
  # nginx reverse proxy
  proxy:
    image: nginx:1.17.10
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/home/app/webapp/staticfiles
      - social_static_volume:/home/app/webapp/social/staticfiles
      - global_static_volume:/home/app/webapp/global/staticfiles
      - gaze_static_volume:/home/app/webapp/gaze/staticfiles
      - aq_static_volume:/usr/share/nginx/html/aq/assets
      - cockpit_static_volume:/usr/share/nginx/html/cockpit/assets
      # - ./nginx/index.html:/usr/share/nginx/html/gaze-tracker/index.html
    ports:
      - "80:80"
    restart: on-failure
    depends_on:
      - cockpit
      - vocal
      - social
      - global
      - gaze
      - questionnaire
    
  # biomarker cockpit service
  cockpit:
    image: cockpit
    # image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/biomarker-cockpit:offline
    pull_policy: always
    container_name: cockpit
    ports:
      - "5000:80"
    volumes:
      - cockpit_static_volume:/usr/share/nginx/html/cockpit/assets
    restart: unless-stopped
    depends_on:
      - keycloak

  # vocal biomarker service
  vocal:
    image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/vocal-biomarker
    # image: vocal
    command: bash -c "python manage.py collectstatic --no-input && gunicorn vocal_biomaker.wsgi:application --bind 0.0.0.0:8001"
    container_name: vocal
    expose:
      - 8001
    volumes:
      - static_volume:/home/app/webapp/staticfiles
      - vocal_data:/home/app/webapp/media/audios
    env_file:
      - ./.env
    restart: on-failure

  # emotional biomarker service
  social:
    image: social
    # image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/social-biomaker:latest
    command: bash -c "python manage.py collectstatic --no-input && gunicorn voice_capt.wsgi:application --bind 0.0.0.0:7000"
    volumes:
        - social_static_volume:/home/app/webapp/social/staticfiles
        - social_data:/home/app/webapp/social/media/videos
    container_name: social
    # environment:
    #   - EMOTION_MONGO_URI=$EMOTION_MONGO_URI
    env_file:
    - ./.env
    expose:
      - 7000
    restart: on-failure
  
  # local-global biomarker service
  global:
    command: bash -c "python manage.py collectstatic --no-input && gunicorn local_global.wsgi:application --bind 0.0.0.0:4000"
    image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/local-global-biomarker:latest
    container_name: global
    environment:
      - GLOBAL_MONGO_URI=$GLOBAL_MONGO_URI
      - DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS
      - DJANGO_DEBUG=$DJANGO_DEBUG
    volumes:
        - global_static_volume:/home/app/webapp/global/staticfiles
    expose:
      - 4000
    restart: on-failure
  
  #gaze service
  gaze:
    # image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/gaze-tracker:latest
    image: gaze
    container_name: gaze
    expose:
      - 9000
    environment:
      - DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS
      - DJANGO_DEBUG=$DJANGO_DEBUG
    volumes:
      - gaze_static_volume:/home/app/webapp/gaze/staticfiles
      - gaze_data:/home/app/webapp/gaze/media
    command: bash -c "python manage.py collectstatic --no-input && gunicorn gaze_tracker.wsgi:application --bind 0.0.0.0:9000"
    restart: on-failure

  #questionnaire service
  questionnaire:
    image: aq-frontend
    # image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/biomarker-questionnaire:offline
    container_name: questionnnaire
    ports:
      - "6000:80"
    restart: on-failure
    volumes:
      - aq_static_volume:/usr/share/nginx/html/assets
    depends_on:
      - aq-backend

  # database service
  mongodb:
    image: mongo:latest
    restart: on-failure
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DB_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db
      - ./.mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  # java authentication
  # java:
  #   image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/biomarker-authentication:latest
  #   container_name: auth
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - auth:/usr/app/target
  #   restart: on-failure
  
  # questionnaire backend service
  aq-backend:
    depends_on:
      - mongodb
      # - keycloak
    container_name: aq-backend
    image: aq-backend
    # image: 715941344009.dkr.ecr.eu-central-1.amazonaws.com/biomarker-questionnaire-backend:latest
    restart: on-failure
    expose:
      - 3001
    env_file:
      - ./.env

  # keycloak service
  keycloak:
    image: wizzn/keycloak:14
    container_name: keycloak
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/jboss/keycloak/standalone/data/
      - ./imports:/opt/jboss/keycloak/imports
    command: 
      - "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    environment:
      - KEYCLOAK_USER='admin'
      - KEYCLOAK_PASSWORD='Gr@C3mwoi'
    restart: on-failure

volumes:
  static_volume:
  social_static_volume:
  global_static_volume:
  gaze_static_volume:
  cockpit_static_volume:
  aq_static_volume:
  db:
  social_data:
  vocal_data:
  keycloak_data:
  gaze_data: