#!/bin/sh
# export PATH=/usr/bin:/bin:$PATH
# function to spin up the containers
spinUp (){
    # open docker if its not open
    if (! docker stats --no-stream ); then
    # On Mac OS this would be the terminal command to launch Docker
    open -a Docker
    #Wait until Docker daemon is running and has completed initialisation
    while (! docker stats --no-stream ); do
    # Docker takes a few seconds to initialize
    echo "Waiting for Docker to launch..."
    sleep 1
    done
    fi
    
    docker run --rm -d -v ~/.aws:/root/.aws amazon/aws-cli ecr get-login-password \
        --region eu-central-1 \
    | docker login \
        --username AWS \
        --password-stdin 715941344009.dkr.ecr.eu-central-1.amazonaws.com
    # docker run --rm -d -v ~/.aws:/root/.aws amazon/aws-cli ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 715941344009.dkr.ecr.eu-central-1.amazonaws.com
    # docker-compose up -d --remove-orphans
}

# check if docker is installed

if [ -x "$(command -v docker)" ]; then
    echo "You already have docker...Good to go!"
else
    echo "Installing docker...."
    if ! command -v brew &>/dev/null; then
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

        if ! grep -qs "recommended by brew doctor" ~/.zshrc; then
            echo "Put Homebrew location earlier in PATH ..."
            export PATH="/usr/local/bin:$PATH"
        fi
    else
        echo "You already have Homebrew installed...good job!"
    fi

    brew install --cask docker
fi

spinUp

